run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/google/uuid
          - github.com/spf13/viper
          - github.com/jmoiron/sqlx
          - github.com/dostrovskiy/otus-golang-home-work/hw12_13_14_15_16_calendar
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/google/uuid
          - github.com/stretchr/testify
          - github.com/dostrovskiy/otus-golang-home-work/hw12_13_14_15_16_calendar
issues:    
  exclude-dirs:
    # от ошибок линтеров на исходники golang в пайплайне github - Error: ../../../../../../opt/hostedtoolcache/go/1.23.4
    - /opt/hostedtoolcache/go/
    # от ошибок линтеров на исходники используемых библиотек в пайплайне github - Error: ../../../../go/pkg/mod/github.com/jackc/pgx@v3.6.2+incompatible/conn.go:1491:6: softErr declared and not used (typecheck)
    - ../../../../go/pkg/mod/
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
